name: Ruby on Rails CI/CD

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: passwordSample
          POSTGRES_DB: embarca_ai_test
        ports:
          - 5432:5432

    env:
      RAILS_ENV: test
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: passwordSample

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0

      - name: Install dependencies
        run: bundle install

      - name: Setup Database
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:create
          bin/rails db:schema:load

      - name: Run Tests
        env:
          RAILS_ENV: test
        run: bundle exec rspec

      - name: Run RuboCop
        run: bundle exec rubocop
